import Head from "next/head";
import Image from "next/image";
import { Inter, Oswald } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import CategorySelector from "@/components/category-selector";
import Tags from "@/components/tags";
import Banner from "@/components/banner";
import SortComponent from "@/components/sort";
import Restaurant from "@/components/restaurant";
import MultipleItems from "@/components/category";
import Layout from "@/components/layout";

const oswald = Oswald({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header />
      <CategorySelector />
      <Tags />
      <Banner /> */}
      <Layout />
      {/* <SortComponent />
      <MultipleItems />
      <Restaurant /> */}
    </>
  );
}
