import Head from "next/head";
import { Inter, Oswald } from "next/font/google";
import Layout from "@/components/layout";

const oswald = Oswald({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>HeyFood App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://heyfood.africa/icons/new/logo-circle-green.svg" />
      </Head>
      <Layout />
    </>
  );
}
